base_url = "https://frozenpizzastudios.com"
output_dir = "docs"
theme = "kita"

compile_sass = false
build_search_index = true

[markdown]
highlight_code = true

# The profile on home page.
[extra.profile]
name = "Frozen Pizza Studios, LLC"
bio = "A small, Minnesota-based game development company"
# The URL of avatar.
avatar_url = "img/logo.png"
# Invert color in dark mode.
avatar_invert = false

# The social icons below the profile on the home page.
# The `name` should be the file name of static/icons/*.svg or the icon name of https://simpleicons.org/
[[extra.profile.social]]
name = "steam"
url = "https://store.steampowered.com/curator/42947587"

[[extra.profile.social]]
name = "twitter"
url = "https://twitter.com/frozenzastudios"

[[extra.profile.social]]
name = "youtube"
url = "https://www.youtube.com/channel/UChQcrZDU9D5o7C5vbkbcciA"

[[extra.profile.social]]
name = "tiktok"
url = "https://www.tiktok.com/@frozenzastudios"

[[extra.profile.social]]
name = "email"
url = "mailto:frozenpizzastudios@gmail.com"

# The top menu.
[[extra.menu]]
name = "Home"
url = "$BASE_URL"

[[extra.menu]]
name = "Games"
url = "$BASE_URL/games"

[[extra.menu]]
name = "Blog"
url = "$BASE_URL/blog"

# The giscus comment options, only available when comment is enabled.
# [extra.giscus]
# repo = ""
# repo_id = ""
# category = ""
# category_id = ""
# mapping = "pathname"
# strict = 1
# reactions_enabled = 0
# emit_metadata = 0
# input_position = "top"
# theme = "light"
# lang = "en"
# loading = "lazy"