title = "Frozen Pizza Studios"
base_url = "https://frozenpizzastudios.com"
output_dir = "docs"

compile_sass = false
build_search_index = true
generate_feeds = false

taxonomies = [
  { name = "tags", feed = false },
]

[markdown]
highlight_code = true
